# Generated by Django 5.1.5 on 2025-01-18 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=350)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sending_datetime', models.DateTimeField()),
                ('mailing_end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Создано'), ('started', 'Запущено'), ('completed', 'Завершено')], default='created', verbose_name='статус')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.message', verbose_name='Сообщение')),
                ('recipients', models.ManyToManyField(to='recipients.recipient', verbose_name='Получатели')),
            ],
        ),
    ]
