# Generated by Django 5.1.5 on 2025-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_sending_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
