# Generated by Django 5.1.5 on 2025-01-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_alter_mailing_user_alter_message_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-first_sending_datetime'], 'permissions': [('can_view_all_mailings', 'Может просматривать все рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'permissions': [('can_view_all_attempts', 'Может просматривать все попытки рассылок')], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_all_messages', 'Может просматривать все сообщения')], 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_view_all_recipients', 'Может просматривать всех получателей')], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
    ]
