# Generated by Django 5.1.5 on 2025-01-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_alter_mailing_options_alter_mailingattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-first_sending_datetime'], 'permissions': [('can_view_all_mailings', 'Может просматривать все рассылки'), ('can_view_mailing_detail', 'Может просматривать детали рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
